### ISSUE TITLE
Websocket tracker ping support

### ISSUE THREAD

**Issue by SilentBot1** [greatest-ape/aquatic#109]
Hey all,

I've ran into an issue today while working with `aquatic-ws@master` in combination with libtorrent. Currently, libtorrent's websocket tracker client implementation is configured to perform a websocket ping [every 10 seconds](https://github.com/arvidn/libtorrent/blob/569960a67dbcbcc1a55ce47e06023bd26c8ed018/src/websocket_stream.cpp#L34), which was not part of the current webtorrent/bittorrent-tracker client implementation.

In the current implementation of `aquatic-ws`, I can see that when a websocket ping message is received, and the log level is set to trace, we get the following messages:
```
2023-01-07T22:35:01.597Z TRACE [tungstenite::protocol] Received message                               
2023-01-07T22:35:01.597Z DEBUG [aquatic_ws::workers::socket] Couldn't parse in_message: Message is nether text nor binary                                                                                 
2023-01-07T22:35:01.597Z TRACE [tungstenite::protocol] Sending pong reply
```
Via a packet capture, I can confirm a websocket pong is returned.

In addition to the pong, due to the failure to parse the above empty message, in what appears to be [this check](https://github.com/greatest-ape/aquatic/blob/0d7119d121d839471d9fd6b17f986ed572ec1520/aquatic_ws_protocol/src/request/mod.rs#L28) within aquatic_ws_protocol, it also disconnects the client with the following error message:
```
{"failure reason":"Invalid request"}
```

As this is not an issue with Aquatic, but rather a non-standard enhancement made within within libtorrent, would websocket pings be something that Aquatic would be interested in supporting?

**Comment by greatest-ape** [comment]
I've merged support.

**Comment by SilentBot1** [comment]
Perfect, thanks for getting this implemented so quickly.

I can confirm this is all working as expected, so will close this down.
