### ISSUE TITLE
Docs for benchmark generation

### ISSUE THREAD

**Issue by crimist** [greatest-ape/aquatic#113]
Nice project! I've written a [bittorrent tracker myself](https://github.com/crimist/trakx) and am curious how it compares to other implementations.

I was wondering if you had automated or created documentation for your tracker benchmarks like the one found at `aquatic/documents/aquatic-udp-load-test-2023-01-11.pdf` so I can reproduce it and add my tracker.

Thanks.

**Comment by greatest-ape** [comment]
Hi!

There is unfortunately no fully automated way of running them yet. There isn’t a lot of documentation, but the load test executables can generate a commented config file.

For instance, run ./scripts/run-load-test-udp.sh -p > udp.toml to generate the config file, then run the script again with -c udp.toml to run load test using the file.

The idea is to start the tracker, run the load test until completion, write down results, stop the tracker, adjust settings (eg number of threads), then repeat.

The most interesting things to adjust will be the server/tracker url, the test duration and the number of workers (i.e. threads). Typically, more workers result in a higher requests/second figure, but only up to a point. You’ll have to test with different numbers.

If you want to limit the tracker to using certain cores, you can use taskset (just don’t forget to take hyperthreads into account.)

**Comment by crimist** [comment]
I see, I'll have to poke around with manual testing when I have time. Appreciate the load test tooling!
