### ISSUE TITLE
[Feature] Add statistics for aquatic-ws

### ISSUE THREAD

**Issue by funniray** [greatest-ape/aquatic#114]
Hi there,

I saw in issue #81 that you mentioned that you would want a [way to monitor the service](https://github.com/greatest-ape/aquatic/issues/81#issuecomment-1186417728). I feel like having support for Prometheus would be a great idea.

Is this something you're still considering?

**Comment by greatest-ape** [comment]
Hi,

Yes, it would definitely make sense.

**Comment by greatest-ape** [comment]
I've merged support.
