### ISSUE TITLE
Lots of Errors

### ISSUE THREAD

**Issue by perfectmovement** [greatest-ape/aquatic#125]
I am getting a lot of errors when I try to ` cargo build --release -p aquatic_udp`

Some errors have detailed explanations: E0283, E0412, E0425, E0432, E0433, E0599.
For more information about an error, try `rustc --explain E0283`.
error: could not compile `privdrop` due to 24 previous errors
warning: build failed, waiting for other jobs to finish...

**Comment by greatest-ape** [comment]
What OS are you using?

**Comment by perfectmovement** [comment]
oh that makes a lot of sense since i am using Windows, thanks!
