### ISSUE TITLE
Aquatic Crash with latest Commit

### ISSUE THREAD

**Issue by bakunin1848** [greatest-ape/aquatic#126]
Rust Version: rustc 1.67.1

Crash :

aquatic_udp[2674874]: thread 'swarm-01' panicked at 'Out of bounds access', /.cargo/registry/src/github.com-1ecc6299db9ec823/indexmap-amortized-1.6.1/src/map/core.rs:615:14
aquatic_udp[2674874]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
aquatic_udp[2674874]: thread 'socket-02' panicked at 'Request channel 0 is disconnected', aquatic_udp/src/common.rs:80:17
aquatic_udp[2674874]: Error: worker thread panicked
aquatic_udp[2674874]: thread 'socket-01' panicked at 'Request channel 0 is disconnected', aquatic_udp/src/common.rs:80:17

**Comment by greatest-ape** [comment]
Thanks!

**Comment by greatest-ape** [comment]
Annoyingly, this seems to be a bug in unmaintained dependency [indexmap-amortized](https://github.com/jonhoo/indexmap-amortized), given that the panic occurs [here](https://github.com/jonhoo/indexmap-amortized/blob/7902615cf1d38927e2e3d7bf5069c59af458c672/src/map/core.rs#L613). I'll have to think about what do about this.

**Comment by greatest-ape** [comment]
Was it running in production when this happened? Could you tell me something about the approximate requests per second, number of peers and time since startup?

**Comment by bakunin1848** [comment]
@greatest-ape 

It was after updating Aquatic today.

The crash is at approximately 2 minutes. Maybe it's a previous commit

The previous version that I have backup works perfectly.

-1M torrents
-1.5M Peers
-1500 Requests/s

**Comment by greatest-ape** [comment]
Thanks!

Do you know the git commit the working version was built from? Otherwise, do you know approximately when you built it?

**Comment by bakunin1848** [comment]
@greatest-ape 

git rev-parse HEAD
5ac8f3727b1edd167cf916bc5242c7c7e9ae4e30

https://github.com/greatest-ape/aquatic/commit/5ac8f3727b1edd167cf916bc5242c7c7e9ae4e30 --> Actual and working Version

**Comment by greatest-ape** [comment]
Thanks. I've dropped use of indexmap-amortized altogether now, which should fix the issues. Since switching to HMAC connection ID validation, amortized index maps likely do not bring many benefits anyways.

**Comment by bakunin1848** [comment]
@greatest-ape 

I just compiled and it's working.

No crash at the moment.

I'll leave it for 24 hours and close the issue but I think it's resolved since before the crash was in the first 2 minutes.

thank you

**Comment by greatest-ape** [comment]
Great!
