### ISSUE TITLE
[feature] Add client versions statistics to Prometheus exporters

### ISSUE THREAD

**Issue by funniray** [greatest-ape/aquatic#139]
The first 8 bytes of a client's peer_id will typically include information about what client/version that peer is running.

Is it possible to include statistics about how many peers are connected with a specific version of a client?

[bittorrent-tracker](https://github.com/webtorrent/bittorrent-tracker) currently exposes this data in its stats page in this format
![image](https://github.com/greatest-ape/aquatic/assets/16416198/0e701b21-ed34-4553-9d1d-b746931c691d)

Edit: For aquatic-ws and aquatic-http, it might be best to also collect the same data, but with user-agent.

**Comment by ThaUnknown** [comment]
https://github.com/webtorrent/bittorrent-peerid/blob/master/index.js#L248

**Comment by greatest-ape** [comment]
Code in https://github.com/greatest-ape/aquatic/pull/141 is ready to try out (for aquatic_udp)!

**Comment by funniray** [comment]
> Code in #141 is ready to try out (for aquatic_udp)!

I'll make sure to test it out when I get the chance. I currently only use aquatic_ws, but I'll see if I can spin up a udp instance and take it for a spin ;)

**Comment by greatest-ape** [comment]
Alright, great!

**Comment by greatest-ape** [comment]
I’ve merged support for udp and ws.

If someone is using the http implementation in at least semi-production and needs this feature, please comment or open a new issue and I’ll consider it.
