### ISSUE TITLE
Question/Feature Request: TLS certificates with aquatic-ws

### ISSUE THREAD

**Issue by SilentBot1** [greatest-ape/aquatic#148]
Hey @greatest-ape, 

Thank you for this awesome project!

I'm currently running a public aquatic-ws server over at [tracker.webtorrent.dev](https://tracker.webtorrent.dev) and this is currently behind a Nginx at the moment so I can both have have certificates automatically managed by certbot, and so the tracker and a website can be served at the same subdomain and route, e.g.
- `https://tracker.webtorrent.dev` shows the metrics page.
- `wss://tracker.webtorrent.dev` is proxied to Aquatic.

(The forwarding logic is based on the `upgrade` header being present or not to determine if this is the start of a WebSocket connection.)

When thinking about the future of the tracker, I see myself running into issues with ephemeral port exhaustion due to the mentioned proxying when combined with the long living nature of WebSocket connections, so I'm looking to move remove the tracker from behind Nginx if feasible (so I don't have to use hacks like listening on `[::]` with Aquatic and forwarding to multiple loopback addresses to get more than ~31k ports/connections).

The one big and little problem that I'm contemplating when looking to move away from Nginx are:
1. No way to reload SSL certificate without restarting the server and losing all swarm state / disconnecting all peers.
2. No way to redirect HTTPs connections away from the tracker.

A few thoughts from my side:
- In regards to `1.` I may be over thinking this, as unlike HTTPs trackers, which would really struggle with a restart due to there being no swarm information for new peers until clients re-announce, WebSocket peers have a very low default announce time and **know** when the tracker has restarted, so can attempt to re-connect and announce again immediately.
- In regards to `2.` this may be a none problem, as I'm unsure how likely a HTTPs client will attempt to navigate to a WSS URL and this may simply be form over function and should be discarded.

Finally the question:
- Would `1.` be a possibly considered feature for both aquatic-ws and aquatic-http?

**Comment by greatest-ape** [comment]
Hi!

I've merged support for reloading TLS files by sending SIGUSR1, for both aquatic_http and aquatic_ws.

When it comes to issue number 2, it would complicate the implementation too much for it to be worthwhile.

**Comment by SilentBot1** [comment]
Awesome, thank you for adding support for this!

I agree, issue 2 very much a nicety and likely not worth the effort or the additional complexity, so I'll close down this issue from my side.

Thanks again!

**Comment by greatest-ape** [comment]
@SilentBot1 would you be ok with me linking to your tracker from the README files?

**Comment by SilentBot1** [comment]
Hey, sure thing, feel free to.

**Comment by greatest-ape** [comment]
> Hey, sure thing, feel free to.

Great!
