### ISSUE TITLE
Question about WS trackers

### ISSUE THREAD

**Issue by kovalensky** [greatest-ape/aquatic#151]
Maybe a strange question, but do websockets trackers work real-time?

So if I connect to the ws tracker requesting data about info-hash, will seeding clients receive my leecher status immediately, bypassing the NAT ~instantly, or is there still some announce interval to wait?

**Comment by kovalensky** [comment]
> Yes. Unlike UDP or HTTP, clients keep a connection to the tracker open at all times.

Thank for the answer, does tracker send leeching clients' info to seeds/partial seeds immediately?
Or there's some technique for sanitizing DDOS attacks involving additional waiting?

**Comment by greatest-ape** [comment]
The tracker will send on your client's WebRTC SDP offers to other peers immediately (maximum number of offers per announce request is configurable).

There is not a lot of DOS protection in aquatic_ws. It can be configured to close connections without meaningful activity after a while. It can be complemented with basic rate limiting with iptables or similar.

**Comment by kovalensky** [comment]
> The tracker will send on your client's WebRTC SDP offers to other peers immediately (maximum number of offers per announce request is configurable).

I see, could clients upgrade connections to say uTP, or only peers with WebRTC connection support are applicable for WebSocket trackers?

I couldn't find a necessary standard document for research, that's why I'm coming up with these questions 😅

**Comment by SilentBot1** [comment]
It was only ever designed for WebRTC capable peers, it would not work for standard uTP or TCP peers in it's current state, though once a wire is established over WebRTC, PEX *would* work for hybrid peers (which support WebRTC + uTP or TCP).

**Comment by kovalensky** [comment]
Sufficient answers, thanks

**Comment by kovalensky** [comment]
> The tracker will send on your client's WebRTC SDP offers to other peers immediately (maximum number of offers per announce request is configurable).

Does the aquatic tracker record peers' port by the &port parameter sent, or uses their actual listening port?
Since &port parameter is not always reliable for NAT restricted peers (clients send configured/random local port but the real one could differ), I think recording their actual port make full-cone, port-restricted peers to connect faster, is that so?
Thanks.

**Comment by greatest-ape** [comment]
@kovalensky aquatic_http and aquatic_udp both use the port sent in the request. The port the request was sent from isn’t necessarily the one the peer wants other peers to connect to, in my understanding. aquatic_ws doesn’t really care about ports, since the mechanism for peer exchange is through SDP offers/answers

I don’t think your NAT idea would work, but I’m unsure. Maybe the libtorrent folks would know?

**Comment by kovalensky** [comment]
@greatest-ape You are right, learned from my bitter experience, clients send announce requests from random ports, to provide concurrency and identify connections.
