### ISSUE TITLE
[bug] aquatic-ws - Prometheus metrics discrepancies

### ISSUE THREAD

**Issue by SilentBot1** [greatest-ape/aquatic#153]
Hi again,

When consuming the Prometheus metrics exported from `aquaitc-ws`, I have noted that over a long period of time, there are "ghost" entries in both the `aquatic_active_connections` and `aquatic_peer_clients` metrics, causing the numbers to not reflect `aquatic_peers` or the number of open tcp sockets on the server.

For example:
![image](https://github.com/greatest-ape/aquatic/assets/15065825/362e7dcf-3689-4598-861b-f5c0fa439a2f)

After a large spike in concurrent peers, all using a specific client, in this case `WebTorrent 0.6`, the number of peers reported in both the `aquatic_peer_clients` and `aquatic_active_connections` metrics do not appear to not fully reflect all of the peers disconnecting until `aquatic-ws` is restarted.

I believe this is a bug, due to the metrics being counts and not incremental values, but I have not been able to identify the specific condition needed to reproduce this issue, but have been noticing this consistently on aquaitc-ws since implementing Prometheus metrics.

**Comment by greatest-ape** [comment]
Thanks.

I couldn't reproduce it, but I did find some issues that could possibly be the cause. I've just merged fixes.

**Comment by SilentBot1** [comment]
After updating and having this running for over the past week, this appears to be fixed: 

![image](https://github.com/greatest-ape/aquatic/assets/15065825/22d00562-c4ca-4eb2-a40d-6b628f76495c)

Thanks again for the fixes.

**Comment by greatest-ape** [comment]
Great!
