### ISSUE TITLE
aquatic with reverse proxy (CDN)

### ISSUE THREAD

**Issue by cherinyy** [greatest-ape/aquatic#156]
Hi there,

I noticed that the Tracker is designed to receive `ip` parameter, but it is optional.

And the most widely used Bittorrent library, `libtorrent`, does not pass the `ip` parameter by default and states "normal trackers don't accept the IP parameter": https://www.libtorrent.org/reference-Settings.html#announce_ip

So I'm wondering if it will be able to HTTP headers like `X-Real-IP` and `X-Forwarded-For` if reverse proxying is done for aquatic? And whether WebTorrent can be reverse proxied, I don't really understand this. Of course, the UDP protocol is not considered here.

Best regards,
Cheriny

**Comment by greatest-ape** [comment]
Hi,

Yes, the IP field is ignored.

Running behind a reverse proxy is supported for WebTorrent, but currently not for HTTP BitTorrent. There is some more info in https://github.com/greatest-ape/aquatic/tree/master/crates/http#configuring and https://github.com/greatest-ape/aquatic/tree/master/crates/ws#configuring.

**Comment by cherinyy** [comment]
Okay, thanks for the answer.

**Comment by greatest-ape** [comment]
@cherinyy I changed my mind about this. I've implemented support for disabling TLS as well as for running behind reverse proxies.

**Comment by cherinyy** [comment]
> @cherinyy I changed my mind about this. I've implemented support for disabling TLS as well as for running behind reverse proxies.

Oh, that's good news for me!
Thank you for your work!
