### ISSUE TITLE
[bug] aquatic-ws - Memory Leak

### ISSUE THREAD

**Issue by SilentBot1** [greatest-ape/aquatic#169]
After leaving an instance of `aquatic-ws` @ e2a321196b81bac903cc5ac7380ce8098911f38d running on a `Ubuntu 22.04.3 LTS` machine, with this [configuration](https://github.com/greatest-ape/aquatic/files/13845036/aquatic-ws-config.txt), it appears there is a memory leak in the `aquatic_ws` process, causing memory usage to increase over the span of multiple days, until the process crashes due to exhausting all system memory (in my case ~2.4GB free - total system memory of 4GB).

An example of peer counts, message throughput and usage can be seen in the following image:
![image](https://github.com/greatest-ape/aquatic/assets/15065825/e45fe92a-0bb5-4747-ad57-a0c5081cc776)

It appears the memory leak is related to peer count in some way, as the memory usage rate increases more under high load, and slows during lower load, but none the less increases over time.

I plan to disable metrics to verify if this could be the cause and will report back if this helps alleviate the issue, but I thought it would be best to open the issue first and provide updates as I try and troubleshoot this.

**Comment by greatest-ape** [comment]
Thanks. I’ve opened an issue in the glommio repository, the async runtime that I’m using. But it would still be great to see the results without metrics. I have a suspicion that https://docs.rs/metrics-exporter-prometheus/latest/metrics_exporter_prometheus/ doesn’t free memory, and I would be I interested in seeing if that is indeed the case and if so, how much of the aquatic leak comes from metrics.

**Comment by SilentBot1** [comment]
Thanks for looking into this and raising an issue with glommio, seems like it will maybe be a difficult one - it's not too critical for me at the moment, as a restart once every 5-7 days isn't too bad, but if/as usage increases, I imagine this will only become more frequent.

For the first 5 hours after a restart, with statistics both enabled and disabled, this is what memory usage looks like:
### Statistics Enabled:
![aoKXUsmt6Y](https://github.com/greatest-ape/aquatic/assets/15065825/64a0d719-83c3-4d27-a513-a7b2d9738d85)
### Statistics Disabled:
![uSQO7cM4wU](https://github.com/greatest-ape/aquatic/assets/15065825/c9d72bc3-51de-4c57-b5ab-308198dd8f31)

In the statistics enabled timeframe, 137k connections were made to the tracker, during the statistics disabled timeframe 175k connections were made to the tracker, so this possibly explains the difference between the two at the end of the 5 hours, as the total usage at the end ended up higher, even with statistics disabled.

It looks like if there is any memory leaking from `metrics_exporter_prometheus` for peer client/prefixes, it's masked entirely by the glommio issue at the moment.

**Comment by greatest-ape** [comment]
Great, thanks. Yes, it might unfortunately take a while to fix this.

**Comment by greatest-ape** [comment]
Actually, I came up with an idea to possibly circumvent the issue. In local testing, it seems to fix the leak. Could you please try out the lastest commit on master?

**Comment by SilentBot1** [comment]
Thank you, I have just updated and restarted - will keep you posted.

**Comment by SilentBot1** [comment]
Just to provide you another 5 hour mark update, things are looking a whole lot better:
![image](https://github.com/greatest-ape/aquatic/assets/15065825/d0dae05d-076c-472f-a72d-95fe7c56dacd)

I will note, metrics now appear to be undulating after the restart:
![image](https://github.com/greatest-ape/aquatic/assets/15065825/812d585f-9dca-4c42-b75d-47c9ae9786a3)

After further looking into this, It only appears to be affecting BitComet peers (which don't actually support WebTorrent, only pulling stats from WebSocket trackers), as they don't appear to be keeping just one socket open continuously: 

![image](https://github.com/greatest-ape/aquatic/assets/15065825/2f5b794a-3e56-4640-bc2c-fe3da48736a4)

**Comment by greatest-ape** [comment]
Excellent!

The undulating BitComet counts are somewhat strange, but by your description, it seems to happen due to the clients acting in a nonstandard way rather than the tracker.

**Comment by SilentBot1** [comment]
Just to provide a further update, it seems like things have continued to work as expected with the provided fix from the 7th onwards:

![image](https://github.com/greatest-ape/aquatic/assets/15065825/ee18cfac-1030-4be2-aac1-94fec7d8400f)

I'll close the issue down as the fix you've implemented has resolved the leak, though if you would like it to track the underlaying glommio issue, feel free to re-open this. 

Thanks again for your help.

**Comment by greatest-ape** [comment]
Great! Thanks for the detailed reports and for trying out the fix.
