### ISSUE TITLE
How can I keep the program running in the background?

### ISSUE THREAD

**Issue by whoisyourvpn** [greatest-ape/aquatic#200]
Currently when I launch the tracker using ` ./target/release/aquatic_udp -c "aquatic-udp-config.toml"` the app shuts down when I close the console. What is the preferred way of keeping the script running persistently in the background? ChatGPT recommends either

`nohup ./target/release/aquatic_udp -c "aquatic-udp-config.toml" &`

or systemd

`sudo nano /etc/systemd/system/aquatic_udp.service`

```
[Unit]
Description=Aquatic UDP BitTorrent Tracker
After=network.target

[Service]
Type=simple
ExecStart=/path/to/target/release/aquatic_udp -c "/path/to/aquatic-udp-config.toml"
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

```
sudo systemctl daemon-reload
sudo systemctl start aquatic_udp.service
sudo systemctl enable aquatic_udp.service
```

or using `screen` or `tmux`. What do you recommend?

**Comment by greatest-ape** [comment]
I would recommend systemd! It makes it easy to start/stop it, and the _enable_ command you mentioned will make it start on boot.
