### ISSUE TITLE
[Crash] Cannot allocate memory

### ISSUE THREAD

**Issue by hexahigh** [greatest-ape/aquatic#204]
Hello, im trying to run aquatic on my rpi4 but im running into a OutOfMemory error, which is odd as i have more than enough free memory to run it.
My build command is `./scripts/env-native-cpu-without-avx-512 && cargo build --release -p aquatic_http`, I also tried  `cargo build --release -p aquatic_http` but that did not work either. According to `free` i have over 5GB of available memory.

The full log is:
```
May 04 13:40:59 raspberrypi aquatic_http[791899]: 13:40:59 [WARN] (swarm-01) glommio::sys::uring: Error: registering buffers in the main ring. SkippingOs {
May 04 13:40:59 raspberrypi aquatic_http[791899]:     code: 12,
May 04 13:40:59 raspberrypi aquatic_http[791899]:     kind: OutOfMemory,
May 04 13:40:59 raspberrypi aquatic_http[791899]:     message: "Cannot allocate memory",
May 04 13:40:59 raspberrypi aquatic_http[791899]: }
```

**Comment by hexahigh** [comment]
I just found out that it only crashes when its run through a systemd service, i don't understand why but i probably did something wrong when creating the service, here is the service file:
```                       
[Unit]
Description=Aquatic start script
After=network.target

[Service]
Type=simple
WorkingDirectory=/home/piax/Documents/tracker
ExecStart=/home/piax/Documents/tracker/aquatic_http -c ./config.conf
User=piax
Group=piax
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

I have used this exact same service file for other programs and they work perfectly.

**Comment by alopatindev** [comment]
Most likely [related](https://github.com/clearlinux/distribution/issues/2372#issuecomment-861757594).
