### ISSUE TITLE
Add `Ord` and `PartialOrd` to the Udp Protocol primitive types.

### ISSUE THREAD

**Issue by da2ce7** [greatest-ape/aquatic#206]
Hello @greatest-ape ,

In Torrust, there are occasions where the only limiting factor from directly using the aquatic primitives is the lack of ordinal compare.

Can you please consider adding the `Ord` and `PartialOrd` derives to all the types in https://github.com/greatest-ape/aquatic/blob/master/crates/udp_protocol/src/common.rs ?

This would make our primitive types types more compatible, and allow us to use these types directly in b-tree's.

Kind Regards,
Cameron.

**Comment by greatest-ape** [comment]
Sure! If you make a PR, I will merge it :-)
