### ISSUE TITLE
Existence of `only_ipv6` is confusing, manging multiple configuration files isn't convenient to just support both protocols

### ISSUE THREAD

**Issue by alopatindev** [greatest-ape/aquatic#210]
Thanks for making this awesome software!

Am I right that running `aquatic_ws` currently requires two separate configuration files if we want it to bind to both IPv4 and IPv6? That's not convenient, in my opinion.

It's also confusing: if configuration file can only support IPv4 or IPv6 exclusively, then what's the point of `only_ipv6` flag? It gives a false hope that turning this flag off will be enough to avoid creating two separate configuration files in this case.

I suppose it's especially confusing to those who aren't willing to read the code or to those who aren't Rust experts who are not aware that `SocketAddr` can't accept both IPv4 and IPv6 and the same time.

It would be nice if we could have a single configuration file in this case and
- either run a single instance that binds to both IPv4 and IPv6
  - `addresses = ["127.0.0.1:3000", "[::1]:3000"]` in config
- or at least two separate instances with  `--address 127.0.0.1:3000` and `--address [::1]:3000` as arguments.

**Comment by zmiguel** [comment]
The UDP and HTTP versions support running both ipv4+ipv6 if you define your address as `address = "[::0.0.0.0]:port"` I haven't used the WS version but did you try this?

**Comment by alopatindev** [comment]
Interesting, this seems to be working for WS version too, thanks.

I'd like to bind specifically to loopback ipv4+ipv6 addresses. Is it possible? Thanks.

**Comment by zmiguel** [comment]
@alopatindev it's based on https://github.com/rust-lang/rust/issues/85609
Perhaps you can get some extra info from here: https://github.com/rust-lang/rust/issues/69772

`::ffff:127.0.0.1` should be v4+v6 loopback address

**Comment by alopatindev** [comment]
Oh, got it, thanks. This works too. I wish that was an example in the readme.
