### ISSUE TITLE
http Logs in aquatic_http 

### ISSUE THREAD

**Issue by ibksturm** [greatest-ape/aquatic#61]
Hi there
other Question

as i understand and since 10 minutes running ([https://ibksturm.synology.me/trackerstats/index.php](https://ibksturm.synology.me/trackerstats/index.php)) aquatic_udp got a html statistic output

does the aquatic_http got also one and i can't find it in config? oder does it simple are in pipeline?

**Comment by greatest-ape** [comment]
aquatic_http currently does not, but I might implement it.

**Comment by ibksturm** [comment]
Cool oki i will wait

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Joakim Frostegård ***@***.***>
Gesendet: Wednesday, March 30, 2022 9:12:04 AM
An: greatest-ape/aquatic ***@***.***>
Cc: Andreas Ziegler ***@***.***>; Author ***@***.***>
Betreff: Re: [greatest-ape/aquatic] http Logs in aquatic_http (Issue #61)


aquatic_http currently does not, but I might implement it.

**Comment by greatest-ape** [comment]
There is now prometheus support for aquatic_http :-)

**Comment by ibksturm** [comment]
Paarty, lets try :)
