### ISSUE TITLE
Tracker reply has no peers field

### ISSUE THREAD

**Issue by R2004GEO** [greatest-ape/aquatic#82]
I want to test aquatic and the torrent clients returns the "Tracker reply has no peers field" status.
Client: uTorrent 2.2.1

**Comment by greatest-ape** [comment]
Thanks.

Are you using aquatic_http?

Could you please share the configuration file?

**Comment by Aranjedeath** [comment]
@R2004GEO can you test this again after updating aquatic? And possibly answer @greatest-ape's questions :)

**Comment by R2004GEO** [comment]
I switched to aquatic_udp, sorry.

**Comment by greatest-ape** [comment]
Alright, and the issues you were having before were with aquatic_http?
